[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mart"
authors = [{ name = "Mart Team", email = "dev@example.com" }]
description = "Custom app template for Frappe v16 and ERPNext v16"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version", "dependencies"]

[tool.setuptools.dynamic]
version = { attr = "mart.__version__" }
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
include = ["mart*"]
